title: Robin Faber # your name (or website title) here
logo: "/images/16825652.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/robinfaber/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-169339535-1 # your Google Analytics tracking ID here
